name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        working-directory: devopsproject
        run: mvn clean package

      - name: Build Docker Image
        working-directory: devopsproject
        run: docker build -t devops-java-app .